name: Panel VPS with Auto Backup + SSH + Playit

on:
  workflow_dispatch:   # manual start
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)

jobs:
  panel:
    runs-on: ubuntu-latest
    timeout-minutes: 350   # ~5h50m, under GitHub’s 6h limit

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.FILEBASE_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.FILEBASE_SECRET_KEY }}
      FILEBASE_BUCKET: ${{ secrets.FILEBASE_BUCKET }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y tmate unzip curl zip screen wget
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Set SSH password
        run: |
          echo "runner:MySecurePass123!" | sudo chpasswd

      - name: Restore Backup from Filebase
        run: |
          mkdir -p panel
          cd panel
          aws --endpoint-url=https://s3.filebase.com s3 cp s3://$FILEBASE_BUCKET/panelbackup.zip panelbackup.zip || echo "No backup found"
          unzip -o panelbackup.zip || echo "No backup found"
          cd ..

      - name: Start SSH + Backup + Playit
        run: |
          chmod +x .github/scripts/ssh_playit_loop.sh
          bash .github/scripts/ssh_playit_loop.sh
